
ActorperSession {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 32
  }
  throughput = 1
}

ActorperAccount {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 128
  }
  throughput = 1
}

ActorperMkd {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 64
  }
  throughput = 1
}

ActorperBolsaStats {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 2
  }
  throughput = 10
}

market.stats {
  enabled = true
  topN = 10
  interval.ms = 10000
}