#################### CONFIG ###############################
path.logs=./logs
islogs=true
websocket.port=8096
min_validate_account=1
zoneId=America/Santiago
#################### SECURITY LIST ###############################
IB.SECURITYLIST=SQM,BSAC,CCU,ENIC,BCH,ECH,QQQM,VT
BCS.SECURITYLIST=CFMINTIPSA,SQM-B,COPEC
sendsecuritylist=true
subscribeSecuritylist_BCS=true
isgenetaltrade=true
bolsa.stats=true
#################### CONEXION ###############################
connections=src/main/resources/connections.json
connectionsmkd=src/main/resources/connectionsmkd.json
#################### BOOK ###############################
max.book=15
max.trade.nemo=500
max.trade.general=500
######################### REDIS ############################### 10:24 ->
redis.host=10.0.1.9
redis.port=6380
redis.password=c#7RyD*p9@Ez
redis.enable.persistencia=true
########################## KEYCLOAK ###################################
url=https://vectortrade.cl/auth
secret=ET0Y7YH2A0JsMzNiwXeWiTeZawmVTvtX
realm=Master
clientid=blotter-front
username=vectortrade
password=ylAYWfhVSw!"#$%$ASEWQWDS
passwordrequiere=true
############################# SQLSERVER ####################################
server.sql=mi-sql-prd-002.5bf1e89c8cf2.database.windows.net
database.sql=capitaria
#username.sql=victornazar
#password.sql=y3IaTn11ih1Q*ivQ
username.sql=javier
password.sql=QWVB1237%&.-2024
requiere.sql=false

prioridad.users=jtolosa,fricci,vnazar,daedo,aanker,\
  agelcich,arodriguez,capitaria,cgarcia,ccovarrubias,\
  dvasquez,dorval,elobo,fcotlar,fgandarillas,fmonti,\
  gaguirre,iarenasb,jelster,jsoffia,jbiotti,jfuenzalida,\
  jibarra,lmoll,mcabanas,minnocenti,mguerrero,mdiaz,mediaz,\
  pcampusano,parrigorriaga,palbornoz,\
  emdoba,vbelmar,ngaray,bnelson,\
  cgutierrez,nbarros,dbarrios,cpareja,fperez,jplarach,jsepulveda,giturra












