fix.config.file=src/main/resources/fix/bcs-initiator.cfg

mongo.uri=mongodb://admin:10wfyaxqxk2hq@68.211.112.146:27017
mongo.database=inyectorcandle

fix.logon.rawData=
fix.logon.username=
fix.logon.password=

candles.timeframes=PT1M,PT5M,PT15M,PT30M,PT1H,PT4H,P1D
rankings.interval=PT30S

fix.marketdata.throttle.ms=0
fix.subscription.pause.ms=5
fix.securitylist.request.type=4
fix.securitylist.scope=ALL

replay.enabled=true
replay.input.path=C:/Users/vnazar/Downloads/bkp-log-inyector/FIX.4.4-FH-BCS-v7-sl-BCSGATEWAY.messages_20260305.log.gz
replay.log.zone=America/Santiago
replay.sleep.ms=0
replay.max.lines=0
replay.preserve.timing=false
replay.timing.speed=1.0
replay.timing.max.sleep.ms=2000
replay.purge.day.before.inject=true
