fix.config.file=E:\\VC-GITHUB\\vector-trade-2.0\\inyectorcandle\\src\\main\\resources\\fix\\bcs-initiator.cfg

mongo.uri=mongodb://admin:10wfyaxqxk2hq@68.211.112.146:27017
mongo.database=inyectorcandle

fix.logon.rawData=MDVECTOR01:IL/tjbT6zGekl9EYCUb5ozY8qI7VxLLaCaUwIr/S0KdiJ2z7/aIPtXDQKWw2kMf6DY9vbRKYMnZ60rGTgRHhTQ==
fix.logon.username=
fix.logon.password=

candles.timeframes=PT1M,PT5M,PT15M,PT30M,PT1H,PT4H,P1D
rankings.interval=PT30S

fix.marketdata.throttle.ms=0
fix.subscription.pause.ms=5
fix.process.snapshots=false
fix.process.snapshot.trades=false
fix.securitylist.request.type=4
fix.securitylist.scope=ALL
fix.subscription.destination.filter=

replay.enabled=true
replay.input.path=C:\\Users\\victo\\Downloads\\log-avn_20260310_131007
replay.log.zone=America/Santiago
replay.sleep.ms=0
replay.max.lines=0
replay.preserve.timing=false
replay.timing.speed=1.0
replay.timing.max.sleep.ms=2000
replay.purge.day.before.inject=true
