candle.websocket.port=8098
candle.websocket.path=/ws/
candle.server.host=localhost

chat.external.host=localhost
chat.external.port=8097
chat.external.path=/ws/

mongo.candle.uri=mongodb://admin:10wfyaxqxk2hq@68.211.112.146:27017
mongo.candle.database=inyectorcandle
mongo.candle.collection=candles
mongo.candle.field.symbol=symbol
mongo.candle.field.timeframe=timeframe
mongo.candle.poll.ms=1000
mongo.candle.batch.size=300
mongo.candle.bootstrap.limit=200
