chat.websocket.port=8097
chat.websocket.path=/ws/
chat.server.host=localhost

candle.external.host=localhost
candle.external.port=8098
candle.external.path=/ws/

view.default.chat.ws.url=ws://localhost:8097/ws/
view.default.candle.ws.url=ws://localhost:8098/ws/
view.default.candle.symbol=SQM
view.default.candle.timeframe=1m

mongo.chat.uri=mongodb://admin:10wfyaxqxk2hq@68.211.112.146:27017
mongo.chat.database=vector_trade
mongo.chat.collection=chat-service-vt
mongo.chat.history.limit=500
