chat.websocket.port=8097
chat.websocket.path=/ws/
chat.server.host=0.0.0.0


view.default.chat.ws.url=ws://0.0.0.0:8097/ws/


mongo.chat.uri=mongodb://admin:10wfyaxqxk2hq@68.211.112.146:27017
mongo.chat.database=vector_trade
mongo.chat.collection=chat-service-vt
mongo.chat.history.limit=500
