url=https://www.vectortrade.cl/updatevt-qa/
shortcutName=VectorTradeQA
company=vc
application=VectorTradeQA
main_class=cl.vc.blotter.MainApp
################## enviroment ####################
localhost=ws://localhost:8096/websocket/
localhost.service=ws://localhost:8096/websocket/
localhost.candle=ws://localhost:8098/ws/
localhost.chat=ws://localhost:8097/ws/
localhost.news=ws://localhost:8099/ws/
################## mensaje de update ################################
forex-symbol=USD/CLP
forex-md-source=DATATEC_XBCL


