url=https://www.vectortrade.cl/updatevt-qa/
shortcutName=VectorTradeQA
company=vc
application=VectorTradeQA
main_class=cl.vc.blotter.MainApp

################## enviroment ####################

production.service=ws://68.211.112.146:8086/websocket/
production.candle=ws://68.211.112.146:8098/ws/
production.chat=ws://68.211.112.146:8197/ws/
production.news=ws://68.211.112.146:8099/ws/

localhost.service=ws://localhost:8096/websocket/
localhost.candle=ws://68.211.112.146:8098/ws/
localhost.chat=ws://68.211.112.146:8197/ws/
localhost.news=ws://68.211.112.146:8099/ws/

arb.service=ws://68.211.112.146:8095/websocket/
arb.candle=ws://68.211.112.146:8098/ws/
arb.chat=ws://68.211.112.146:8197/ws/
arb.news=ws://68.211.112.146:8099/ws/

################## mensaje de update ################################
forex-symbol=USD/CLP
forex-md-source=DATATEC_XBCL


