url=http://172.16.0.6:8092/updatevtautoupdate
shortcutName=VectorTrade
company=vc
application=VectorTrade
update.packId=VectorTrade2
main_class=cl.vc.blotter.MainApp
version=2.0.0

################## enviroment ####################

production=ws://172.16.0.6:8096/ws/
production.candle=ws://172.16.0.6:8098/ws/
production.chat=ws://172.16.0.6:8097/ws/
production.news=ws://172.16.0.6:8100/ws/

################## mensaje de update ################################
forex-symbol=USD/CLP
forex-md-source=DATATEC_XBCL
